"""Shared helpers for the tests that build a dashboard page to a temporary folder and open it in a
headless Edge session (tests/test_reader_text.py, tests/test_inventory_page_browser.py,
tests/test_dynamic_values.py).

Process safety: each Edge is launched by these tests on its own temp profile with its own
remote-debugging port; only that process (by PID) is closed and its profile deleted. No browser is
ever closed by name.

Charting library: the pages load Plotly from a CDN. Here the CDN request is answered with an empty
script (cdn="stub", no console error) and a stand-in Plotly records every chart's traces in
window.__plots, so the tests run offline and can read chart data; cdn="fail" makes the request
fail, to test the page with no charting library.
"""
import base64
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request

import pytest

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))
TRACKED_INVENTORY_HTML = os.path.join(PROJECT_ROOT, "forecast", "inventory.html")

PLOTLY_STUB = ("window.__plots={};window.Plotly={newPlot:function(id,d,l){window.__plots[id]=d;},"
               "react:function(id,d,l){window.__plots[id]=d;}};")


def fresh_inventory_data() -> dict:
    """The tracked page's embedded data, with every database-free reader text regenerated by the builder."""
    import build_inventory_page_data as bd
    with open(TRACKED_INVENTORY_HTML, encoding="utf-8") as f:
        text = f.read()
    m = re.search(r'<script type="application/json" id="inventory-data">(.*?)</script>', text, re.DOTALL)
    assert m, "embedded inventory-data block not found in the tracked inventory.html"
    data = json.loads(m.group(1))
    bd.apply_reader_text(data)
    return data


TRACKED_STOCK_JSON = os.path.join(PROJECT_ROOT, "data", "stock_daily.json")


def load_stock_payload() -> dict:
    """The tracked stock file the Min-Max page loads (data/stock_daily.json, written by the daily job and the monthly runner)."""
    import stock_daily
    if not os.path.exists(TRACKED_STOCK_JSON):
        pytest.skip("SKIPPED, not passed: data/stock_daily.json does not exist yet (the daily job or the monthly runner writes it)")
    return stock_daily.read_payload(TRACKED_STOCK_JSON)


def write_stock_file(site_dir: str, payload: dict) -> str:
    """Writes payload as <site_dir>/data/stock_daily.json, where a page at <site_dir>/forecast/inventory.html loads it from."""
    import stock_daily
    return stock_daily.write_payload(payload, os.path.join(site_dir, "data", "stock_daily.json"))


def build_inventory_html(out_path: str, stock="tracked") -> str:
    """Builds the inventory page with build_inventory_page.build_page() to out_path (no database), in a temporary site
    layout: the stock file the page loads at runtime is written to ../data/stock_daily.json next to the page's folder.
    stock = "tracked" (the repository's own stock file), a payload dict, or None (no stock file: the page shows its
    'could not load' message)."""
    import build_inventory_page as bp
    mp = pytest.MonkeyPatch()
    data = fresh_inventory_data()
    mp.setattr(bp, "build_data", lambda **kw: data)
    try:
        page = bp.build_page()
    finally:
        mp.undo()
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(page)
    if stock is not None:
        payload = load_stock_payload() if isinstance(stock, str) else stock
        write_stock_file(os.path.dirname(os.path.dirname(os.path.abspath(out_path))), payload)
    return out_path


def find_edge():
    for c in (os.environ.get("EDGE_PATH"),
              r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
              r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"):
        if c and os.path.exists(c):
            return c
    return None


def file_url(path):
    return "file:///" + os.path.abspath(path).replace("\\", "/")


def require_browser():
    """Returns the Edge path, or skips the calling test with a clear message."""
    try:
        import websocket  # noqa: F401
    except ImportError:
        pytest.skip("SKIPPED, not passed: websocket-client is not installed, so no browser test can run")
    exe = find_edge()
    if not exe:
        pytest.skip("SKIPPED, not passed: Microsoft Edge was not found (set EDGE_PATH), so no browser test can run")
    return exe


class Edge:
    """Own headless Edge on a temp profile; only its own PID is closed."""

    def __init__(self, exe):
        import websocket
        self._ws_mod = websocket
        s = socket.socket()
        s.bind(("127.0.0.1", 0))
        self.port = s.getsockname()[1]
        s.close()
        self.profile = tempfile.mkdtemp(prefix="page_test_edge_")
        self.proc = subprocess.Popen(
            [exe, f"--remote-debugging-port={self.port}", f"--user-data-dir={self.profile}", "--headless=new",
             "--no-first-run", "--no-default-browser-check", "--allow-file-access-from-files", "about:blank"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        self.pid = self.proc.pid
        self.ws, self._id, self.errors, self._tab = None, 0, [], None
        for _ in range(60):
            try:
                urllib.request.urlopen(f"http://127.0.0.1:{self.port}/json/version", timeout=1).read()
                return
            except Exception:
                time.sleep(0.5)
        self.close()
        raise RuntimeError("Edge did not start")

    # -- protocol
    def _handle_event(self, m):
        method, p = m.get("method"), m.get("params", {})
        if method == "Fetch.requestPaused":
            rid = p["requestId"]
            self._id += 1
            if self._cdn == "fail":
                msg = {"id": self._id, "method": "Fetch.failRequest", "params": {"requestId": rid, "errorReason": "ConnectionRefused"}}
            else:
                msg = {"id": self._id, "method": "Fetch.fulfillRequest",
                       "params": {"requestId": rid, "responseCode": 200,
                                  "responseHeaders": [{"name": "Content-Type", "value": "application/javascript"}],
                                  "body": base64.b64encode(b"").decode()}}
            self.ws.send(json.dumps(msg))
        elif method == "Runtime.exceptionThrown":
            d = p["exceptionDetails"]
            self.errors.append(f"exception: {(d.get('exception') or {}).get('description') or d.get('text')} "
                               f"(line {d.get('lineNumber')})")
        elif method == "Log.entryAdded" and p["entry"]["level"] == "error":
            self.errors.append(f"log error: {p['entry']['text']}")
        elif method == "Runtime.consoleAPICalled" and p["type"] == "error":
            self.errors.append("console.error: " + " ".join(str(a.get("value", a.get("description", ""))) for a in p["args"]))

    def call(self, method, **params):
        self._id += 1
        mid = self._id
        self.ws.send(json.dumps({"id": mid, "method": method, "params": params}))
        while True:
            m = json.loads(self.ws.recv())
            if m.get("id") == mid:
                return m
            if "method" in m:
                self._handle_event(m)

    def pump(self, seconds=0.4):
        end = time.time() + seconds
        self.ws.settimeout(0.1)
        try:
            while time.time() < end:
                try:
                    m = json.loads(self.ws.recv())
                except Exception:
                    continue
                if "method" in m:
                    self._handle_event(m)
        finally:
            self.ws.settimeout(60)

    def open(self, path, width=1440, height=900, mobile=False, cdn="stub"):
        self._cdn = cdn
        if self.ws:
            self.ws.close()
            if self._tab:
                try:
                    urllib.request.urlopen(f"http://127.0.0.1:{self.port}/json/close/{self._tab}", timeout=5).read()
                except Exception:
                    pass
        req = urllib.request.Request(f"http://127.0.0.1:{self.port}/json/new?about:blank", method="PUT")
        tab = json.load(urllib.request.urlopen(req))
        self._tab = tab["id"]
        self.ws = self._ws_mod.create_connection(tab["webSocketDebuggerUrl"], timeout=60, suppress_origin=True)
        self.errors = []
        self.call("Runtime.enable")
        self.call("Log.enable")
        self.call("Page.enable")
        self.call("Emulation.setDeviceMetricsOverride", width=width, height=height, deviceScaleFactor=1, mobile=mobile)
        self.call("Fetch.enable", patterns=[{"urlPattern": "*cdnjs.cloudflare.com*"}])
        if cdn == "stub":
            self.call("Page.addScriptToEvaluateOnNewDocument", source=PLOTLY_STUB)
        self.call("Page.navigate", url=path if str(path).startswith("http://127.0.0.1") else file_url(path))
        for _ in range(80):
            if self.ev("document.readyState") == "complete":
                break
            time.sleep(0.25)
        self.pump(0.6)

    def ev(self, expr):
        r = self.call("Runtime.evaluate", expression=expr, returnByValue=True)["result"]
        if "exceptionDetails" in r:
            raise RuntimeError(json.dumps(r["exceptionDetails"], ensure_ascii=False)[:500])
        return r["result"].get("value")

    def close(self):
        try:
            if self.ws:
                self.ws.close()
        except Exception:
            pass
        subprocess.run(["taskkill", "/PID", str(self.pid), "/T", "/F"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(1)
        shutil.rmtree(self.profile, ignore_errors=True)
