"""Guards for reader-facing text (CONVENTIONS.md "Reader-facing text", .claude/skills/reader-text/SKILL.md).

What a reader can see on forecast/sales_report.html and forecast/inventory.html must not carry
project internals: no file extension (.py .md .csv .yaml .json ...), no METRICS / DATA_MAP /
STATUS.md word, no section reference (§ or Sec. followed by a number), no config key, and no
line of more than 60 characters without any Thai.

Both pages are rebuilt into a pytest tmp_path by the same builders the monthly runner uses
(src/build_report.build_report(output_path=...) and src/build_inventory_page.build_page()); no
tracked file is written. build_inventory_page needs database pulls, so its data block is taken
from the tracked page's embedded JSON, with every reader-facing text field that the builder
produces without a database regenerated by build_inventory_page_data.apply_reader_text().

Two views are checked:
  * static  -- the HTML with scripts, styles and comments removed;
  * rendered -- the text Edge actually shows after the page's own JS ran (every inventory
    division), with Plotly stubbed and the CDN blocked so the run is offline. Skipped when Edge
    is not installed.

There are no exceptions: PENDING_REWRITE is empty and every reader-facing line must pass.
"""
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
from html.parser import HTMLParser

import pytest
import yaml

from page_helpers import Edge, build_inventory_html, file_url, require_browser

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))
CONFIG_PATH = os.path.join(PROJECT_ROOT, "config", "config.yaml")
TRACKED_INVENTORY_HTML = os.path.join(PROJECT_ROOT, "forecast", "inventory.html")

THAI = re.compile(r"[\u0E00-\u0E7F]")
FILE_EXT = re.compile(r"\.(?:py|md|csv|yaml|yml|json|html|xlsx|js)\b", re.I)
INTERNAL_WORDS = re.compile(r"METRICS|DATA_MAP|PROJECT_GRAPH|STATUS\.md|CONVENTIONS")
SECTION_REF = re.compile(r"(?:§|\bSec\.|\bsection)\s*\d+", re.I)
INTERNAL_NAMES = re.compile(r"\b(?:stock_policy|confirmed_to_order|finished_goods_stock|component_stock_ato)\b")
MAX_NON_THAI_LINE = 60

# No exceptions: every reader-facing line must pass the rules.
PENDING_REWRITE = []


def _config_keys() -> set:
    with open(CONFIG_PATH, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    keys = set()

    def walk(node):
        if isinstance(node, dict):
            for k, v in node.items():
                if isinstance(k, str) and "_" in k and len(k) >= 6:
                    keys.add(k)
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(cfg)
    return keys


def violations(lines, config_keys) -> list:
    """Every rule hit in `lines` (already stripped of scripts, styles and comments)."""
    key_re = re.compile(r"(?<![A-Za-z0-9_])(?:" + "|".join(map(re.escape, sorted(config_keys, key=len, reverse=True))) + r")(?![A-Za-z0-9_])")
    found = []
    for raw in lines:
        line = " ".join(raw.split())
        for pat in PENDING_REWRITE:
            line = pat.sub("", line)
        line = line.strip()
        if not line:
            continue
        for name, pat in [("file extension", FILE_EXT), ("internal word", INTERNAL_WORDS),
                          ("section reference", SECTION_REF), ("internal status name", INTERNAL_NAMES),
                          ("config key", key_re)]:
            m = pat.search(line)
            if m:
                found.append(f"{name} {m.group(0)!r} in: {line[:120]}")
        if len(line) > MAX_NON_THAI_LINE and not THAI.search(line):
            found.append(f"line over {MAX_NON_THAI_LINE} chars with no Thai: {line[:120]}")
    return found


class _VisibleText(HTMLParser):
    """Visible text lines: scripts, styles, comments and <head> dropped; inline tags do not break a line."""
    SKIP = {"script", "style", "head", "template"}
    INLINE = {"b", "i", "em", "strong", "code", "span", "a", "small", "sub", "sup", "u", "font"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.lines, self._cur, self._skip = [], [], 0

    def _flush(self):
        text = " ".join("".join(self._cur).split())
        if text:
            self.lines.append(text)
        self._cur = []

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self._skip += 1
        elif tag not in self.INLINE:
            self._flush()

    def handle_endtag(self, tag):
        if tag in self.SKIP:
            self._skip = max(0, self._skip - 1)
        elif tag not in self.INLINE:
            self._flush()

    def handle_data(self, data):
        if not self._skip:
            self._cur.append(data)

    def close(self):
        super().close()
        self._flush()


def visible_lines(html_text: str) -> list:
    p = _VisibleText()
    p.feed(html_text)
    p.close()
    return p.lines


# ------------------------------------------------------------------ building pages to tmp

@pytest.fixture(scope="module")
def built_pages(tmp_path_factory):
    import build_report
    out = tmp_path_factory.mktemp("reader_text")
    sales = build_report.build_report(output_path=str(out / "sales_report.html"))
    inv = build_inventory_html(str(out / "inventory.html"))
    return {"sales_report": sales, "inventory": inv}


# ------------------------------------------------------------------ static view

@pytest.mark.parametrize("page", ["sales_report", "inventory"])
def test_static_visible_text_is_reader_text(page, built_pages):
    with open(built_pages[page], encoding="utf-8") as f:
        lines = visible_lines(f.read())
    assert len(lines) > 20, f"{page}: visible text extraction looks empty"
    found = violations(lines, _config_keys())
    assert not found, f"{page}: reader-facing text carries project internals:\n" + "\n".join(found)


def test_guard_catches_each_rule():
    """The guard itself: one sample per rule must be caught, and Thai text must pass."""
    keys = {"segment_policy"}
    assert violations(["ดูที่ build_report.py"], keys)
    assert violations(["ตามเอกสาร METRICS"], keys)
    assert violations(["ตาม Sec.23 ของโครงการ"], keys)
    assert violations(["ตาม § 40"], keys)
    assert violations(["แก้ segment_policy ก่อน"], keys)
    assert violations(["x" * 30 + " " + "y" * 40], keys)
    assert not violations(["ตัวควบคุมด้านล่างเปลี่ยนแค่ตัวเลขบนหน้านี้ ไม่ได้เปลี่ยนการทายยอดขาย"], keys)
    assert not violations(["Min/Max ไม่เปลี่ยน เพราะคำนวณจากยอดขาย ไม่ได้ใช้ stock ปัจจุบัน " + "a" * 70], keys)


def test_visible_text_extraction_drops_scripts_styles_and_comments():
    lines = visible_lines("<html><head><title>x.py</title></head><body><!-- a.py --><p>สวัสดี <b>ครับ</b></p>"
                          "<script>var f='b.csv'</script><style>.c{}</style><div>ต่อ</div></body></html>")
    assert lines == ["สวัสดี ครับ", "ต่อ"]


# ------------------------------------------------------------------ rendered view (Edge)

@pytest.fixture(scope="module")
def rendered_texts(built_pages):
    exe = require_browser()
    texts = {}
    edge = Edge(exe)
    try:
        edge.open(built_pages["sales_report"])
        texts["sales_report"] = edge.ev("document.body.innerText")
        edge.open(built_pages["inventory"])
        for division in ("PEM101", "PEM103", "PEM107"):
            edge.ev(f"document.getElementById('division-select').value='{division}'; onDivisionChange(); 1")
            time.sleep(0.5)
            texts[f"inventory {division}"] = edge.ev("document.body.innerText")
        assert not edge.errors, f"console errors while rendering: {edge.errors}"
    finally:
        edge.close()
    return texts


@pytest.mark.parametrize("view", ["sales_report", "inventory PEM101", "inventory PEM103", "inventory PEM107"])
def test_rendered_text_is_reader_text(view, rendered_texts):
    lines = re.split(r"[\n\t]", rendered_texts[view])  # innerText joins table cells with tabs
    assert len(lines) > 20, f"{view}: rendered text looks empty"
    found = violations(lines, _config_keys())
    assert not found, f"{view}: rendered reader-facing text carries project internals:\n" + "\n".join(found)
