"""Guards for reader-facing text (CONVENTIONS.md "Reader-facing text", .claude/skills/reader-text/SKILL.md).

What a reader can see on forecast/sales_report.html and forecast/inventory.html must not carry
project internals: no file extension (.py .md .csv .yaml .json ...), no METRICS / DATA_MAP /
STATUS.md word, no section reference (§ or Sec. followed by a number), no config key, and no
line of more than 60 characters without any Thai.

Both pages are rebuilt into a pytest tmp_path by the same builders the monthly runner uses
(src/build_report.build_report(output_path=...) and src/build_inventory_page.build_page()); no
tracked file is written. build_inventory_page needs database pulls, so its data block is taken
from the tracked page's embedded JSON, with every reader-facing text field that the builder
produces without a database regenerated by build_inventory_page_data.apply_reader_text().

Two views are checked:
  * static  -- the HTML with scripts, styles and comments removed;
  * rendered -- the text Edge actually shows after the page's own JS ran (every inventory
    division), with Plotly stubbed and the CDN blocked so the run is offline. Skipped when Edge
    is not installed.

There are no exceptions: PENDING_REWRITE is empty and every reader-facing line must pass.
"""
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
from html.parser import HTMLParser

import pytest
import yaml

from page_helpers import Edge, build_inventory_html, file_url, require_browser

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))
CONFIG_PATH = os.path.join(PROJECT_ROOT, "config", "config.yaml")
TRACKED_INVENTORY_HTML = os.path.join(PROJECT_ROOT, "forecast", "inventory.html")

THAI = re.compile(r"[\u0E00-\u0E7F]")
FILE_EXT = re.compile(r"\.(?:py|md|csv|yaml|yml|json|html|xlsx|js)\b", re.I)
INTERNAL_WORDS = re.compile(r"METRICS|DATA_MAP|PROJECT_GRAPH|STATUS\.md|CONVENTIONS")
SECTION_REF = re.compile(r"(?:§|\bSec\.|\bsection)\s*\d+", re.I)
INTERNAL_NAMES = re.compile(r"\b(?:stock_policy|confirmed_to_order|finished_goods_stock|component_stock_ato)\b")
TABLE_NAME = re.compile(r"\b[Cc]ube_\w+")
TASK_REF = re.compile(r"\btask\s*\d+[a-z]?\b", re.I)
MAX_NON_THAI_LINE = 60

# No exceptions: every reader-facing line must pass the rules.
PENDING_REWRITE = []


def _config_keys() -> set:
    with open(CONFIG_PATH, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    keys = set()

    def walk(node):
        if isinstance(node, dict):
            for k, v in node.items():
                if k == "exceptions":
                    continue                      # its keys are item codes (material_plan.non_stock_rule.exceptions): codes are shown on the pages by design
                if isinstance(k, str) and "_" in k and len(k) >= 6:
                    keys.add(k)
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(cfg)
    return keys


def violations(lines, config_keys, english_exempt=frozenset()) -> list:
    """Every rule hit in `lines` (already stripped of scripts, styles and comments). `english_exempt` holds lines that
    are table cells (product names and descriptions from the price list): the English-only-line rule skips them, every
    other rule still applies."""
    key_re = re.compile(r"(?<![A-Za-z0-9_])(?:" + "|".join(map(re.escape, sorted(config_keys, key=len, reverse=True))) + r")(?![A-Za-z0-9_])")
    found = []
    cleaned = [" ".join(raw.split()) for raw in lines]
    for i, raw in enumerate(lines):
        line = " ".join(raw.split())
        for pat in PENDING_REWRITE:
            line = pat.sub("", line)
        line = line.strip()
        if not line:
            continue
        for name, pat in [("file extension", FILE_EXT), ("internal word", INTERNAL_WORDS),
                          ("section reference", SECTION_REF), ("internal status name", INTERNAL_NAMES),
                          ("table name", TABLE_NAME), ("task reference", TASK_REF), ("config key", key_re)]:
            m = pat.search(line)
            if m:
                found.append(f"{name} {m.group(0)!r} in: {line[:120]}")
        # an English term or sentence is allowed where Thai would confuse, with a short Thai explanation next to it (decision of 2026-10-09): the line before or after has Thai
        has_thai_neighbour = any(0 <= j < len(cleaned) and THAI.search(cleaned[j]) for j in (i - 1, i + 1))
        if len(line) > MAX_NON_THAI_LINE and not THAI.search(line) and line not in english_exempt and not has_thai_neighbour:
            found.append(f"line over {MAX_NON_THAI_LINE} chars with no Thai: {line[:120]}")
    return found


class _VisibleText(HTMLParser):
    """Visible text lines: scripts, styles, comments and <head> dropped; inline tags do not break a line."""
    SKIP = {"script", "style", "head", "template"}
    INLINE = {"b", "i", "em", "strong", "code", "span", "a", "small", "sub", "sup", "u", "font"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.lines, self._cur, self._skip = [], [], 0

    def _flush(self):
        text = " ".join("".join(self._cur).split())
        if text:
            self.lines.append(text)
        self._cur = []

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self._skip += 1
        elif tag not in self.INLINE:
            self._flush()

    def handle_endtag(self, tag):
        if tag in self.SKIP:
            self._skip = max(0, self._skip - 1)
        elif tag not in self.INLINE:
            self._flush()

    def handle_data(self, data):
        if not self._skip:
            self._cur.append(data)

    def close(self):
        super().close()
        self._flush()


def visible_lines(html_text: str) -> list:
    p = _VisibleText()
    p.feed(html_text)
    p.close()
    return p.lines


# ------------------------------------------------------------------ building pages to tmp

@pytest.fixture(scope="module")
def built_pages(tmp_path_factory):
    import build_report
    out = tmp_path_factory.mktemp("reader_text")
    sales = build_report.build_report(output_path=str(out / "sales_report.html"))
    inv = build_inventory_html(str(out / "forecast" / "inventory.html"))
    return {"sales_report": sales, "inventory": inv}


@pytest.fixture(scope="module")
def plan_page(tmp_path_factory):
    """forecast/operation_plan.html built by its builder from the recorded plan into a temporary folder (skipped where the recorded plan is absent)."""
    import build_operation_plan_page as bp
    import operation_plan as op
    cfg = op.load_config()
    for k in ("output_item_month_file", "output_division_month_file", "output_meta_file", "output_integrity_file"):
        if not os.path.exists(op.path_of(PROJECT_ROOT, cfg[k])):
            pytest.skip("SKIPPED, not passed: the recorded operation plan is not on this machine")
    out = tmp_path_factory.mktemp("reader_text_plan")
    return bp.build_page(out_path=str(out / "forecast" / "operation_plan.html"))


# ------------------------------------------------------------------ static view

@pytest.mark.parametrize("page", ["sales_report", "inventory"])
def test_static_visible_text_is_reader_text(page, built_pages):
    with open(built_pages[page], encoding="utf-8") as f:
        lines = visible_lines(f.read())
    assert len(lines) > 20, f"{page}: visible text extraction looks empty"
    import html as _html
    with open(built_pages[page], encoding="utf-8") as f:
        # item rows of the forward forecast table read "code name", the name coming from the price list (exempt from the English-only-line rule only)
        names = {" ".join(_html.unescape(f"{c} {n}").split()) for c, n in re.findall(r'<td>([^<]+) <span class="fwd-name">(.*?)</span></td>', f.read())}
    found = violations(lines, _config_keys(), english_exempt=names)
    assert not found, f"{page}: reader-facing text carries project internals:\n" + "\n".join(found)


def test_guard_catches_each_rule():
    """The guard itself: one sample per rule must be caught, and Thai text must pass."""
    keys = {"segment_policy"}
    assert violations(["ดูที่ build_report.py"], keys)
    assert violations(["ตามเอกสาร METRICS"], keys)
    assert violations(["ตาม Sec.23 ของโครงการ"], keys)
    assert violations(["ตาม § 40"], keys)
    assert violations(["แก้ segment_policy ก่อน"], keys)
    assert violations(["x" * 30 + " " + "y" * 40], keys)
    assert violations(["ข้อมูลจาก cube_Sale_APD"], keys)
    assert violations(["ข้อมูลจาก Cube_CES"], keys)
    assert violations(["เพิ่มเมื่อ task 2a"], keys)
    english = "Relative MAE is our MAE divided by the MAE of the Naive forecast on the same items"
    assert violations([english], keys)                                                                  # an English sentence alone still fails
    assert not violations([english, "ต่ำกว่า 1 = ดีกว่า Naive"], keys) and not violations(["Tracking Signal", english, "คือความคลาดสะสม"], keys)   # with a Thai explanation next to it it passes
    assert violations([english, "x" * 30 + " " + "y" * 40], keys)                                      # a neighbour with no Thai is no explanation
    long_cell = "3 Phase 1000kVA 22kV 400/230V Dyn11 Low Loss (Total Loss 1.2%) 008 PEA"
    assert violations([long_cell], keys) and not violations([long_cell], keys, english_exempt={long_cell})
    assert not violations(["ตัวควบคุมด้านล่างเปลี่ยนแค่ตัวเลขบนหน้านี้ ไม่ได้เปลี่ยนการทายยอดขาย"], keys)
    assert not violations(["Min/Max ไม่เปลี่ยน เพราะคำนวณจากยอดขาย ไม่ได้ใช้ stock ปัจจุบัน " + "a" * 70], keys)


def test_visible_text_extraction_drops_scripts_styles_and_comments():
    lines = visible_lines("<html><head><title>x.py</title></head><body><!-- a.py --><p>สวัสดี <b>ครับ</b></p>"
                          "<script>var f='b.csv'</script><style>.c{}</style><div>ต่อ</div></body></html>")
    assert lines == ["สวัสดี ครับ", "ต่อ"]


# ------------------------------------------------------------------ rendered view (Edge)

@pytest.fixture(scope="module")
def rendered_texts(built_pages):
    exe = require_browser()
    texts = {}
    edge = Edge(exe)
    try:
        edge.open(built_pages["sales_report"])
        texts["sales_report"] = edge.ev("document.body.innerText")
        edge.open(built_pages["inventory"])
        for division in ("PEM101", "PEM103", "PEM107"):
            edge.ev(f"document.getElementById('division-select').value='{division}'; onDivisionChange(); 1")
            time.sleep(0.5)
            texts[f"inventory {division}"] = edge.ev("document.body.innerText")
        assert not edge.errors, f"console errors while rendering: {edge.errors}"
    finally:
        edge.close()
    return texts


@pytest.mark.parametrize("view", ["sales_report", "inventory PEM101", "inventory PEM103", "inventory PEM107"])
def test_rendered_text_is_reader_text(view, rendered_texts):
    lines = re.split(r"[\n\t]", rendered_texts[view])  # innerText joins table cells with tabs
    assert len(lines) > 20, f"{view}: rendered text looks empty"
    found = violations(lines, _config_keys())
    assert not found, f"{view}: rendered reader-facing text carries project internals:\n" + "\n".join(found)


# ------------------------------------------------------------------ index.html (phase W3): every tab, rendered
# The S&OP tab's original-file figures are a documented exception to CONVENTIONS.md "Dynamic values" until phase S
# rebuilds that tab from the database: they stay as they are and the tab says so in a notice at its top. The reader-text
# rules below apply to that tab's text all the same. Product names and descriptions in table cells come from the price
# list and are exempt from the English-only-line rule only; every other rule applies to them too.
INDEX_VIEWS = {
    "S&OP": ("origTab", None),
    "Trend": ("omniTab", "omniShowTab(2)"),
    "Manual": ("manualTab", "omniShowTab(3)"),
    "Assumptions": ("assumptionsTab", "omniShowTab(4)"),
    "Stock panel": ("invPanel", "omniShowTab(1); document.getElementById('invMenuRow').click()"),
}


def _make_index_site(site_dir):
    """A temporary copy of what index.html loads at runtime: the page, the manual, the stock data file and the assumptions file."""
    import shutil
    os.makedirs(os.path.join(site_dir, "docs"), exist_ok=True)
    os.makedirs(os.path.join(site_dir, "data"), exist_ok=True)
    shutil.copy(os.path.join(PROJECT_ROOT, "index.html"), os.path.join(site_dir, "index.html"))
    shutil.copy(os.path.join(PROJECT_ROOT, "docs", "user_manual.md"), os.path.join(site_dir, "docs", "user_manual.md"))
    shutil.copy(os.path.join(PROJECT_ROOT, "data", "inventory.json"), os.path.join(site_dir, "data", "inventory.json"))
    shutil.copy(os.path.join(PROJECT_ROOT, "data", "assumptions.json"), os.path.join(site_dir, "data", "assumptions.json"))


class _Quiet(__import__("http.server").server.SimpleHTTPRequestHandler):
    def log_message(self, *a):
        pass


@pytest.fixture(scope="module")
def index_url(tmp_path_factory):
    import functools
    import http.server
    import threading
    site = tmp_path_factory.mktemp("index_w3")
    _make_index_site(str(site))
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), functools.partial(_Quiet, directory=str(site)))
    threading.Thread(target=server.serve_forever, daemon=True).start()
    yield f"http://127.0.0.1:{server.server_address[1]}/index.html"
    server.shutdown()


@pytest.fixture(scope="module")
def index_texts(index_url):
    exe = require_browser()
    texts, cells = {}, {}
    edge = Edge(exe)
    try:
        edge.open(index_url)
        time.sleep(1.5)
        for view, (container, action) in INDEX_VIEWS.items():
            if action:
                edge.ev(action + "; 1")
            deadline = time.time() + 30
            while time.time() < deadline:
                text = edge.ev(f"document.getElementById('{container}').innerText")
                loading = ("กำลังโหลด" in text and container in ("manualTab", "invPanel")) or len(text) < 50
                if not loading and (container != "invPanel" or edge.ev("document.getElementById('invContent').style.display") == "block"):
                    break
                time.sleep(0.5)
            time.sleep(0.5)
            texts[view] = edge.ev(f"document.getElementById('{container}').innerText")
            cells[view] = set(edge.ev(f"[...document.querySelectorAll('#{container} td, #{container} th')].map(c => c.innerText.trim())"))
            if container == "invPanel":     # the popup behind a Reserved figure is part of the panel
                edge.ev("document.querySelector('.inv-bl-btn').click(); 1")
                time.sleep(0.5)
                texts["Stock panel popup"] = edge.ev("document.getElementById('invBlModal').innerText")
                cells["Stock panel popup"] = set(edge.ev("[...document.querySelectorAll('#invBlModal td, #invBlModal th')].map(c => c.innerText.trim())"))
        script_errors = [e for e in edge.errors if e.startswith("exception")]
        assert not script_errors, f"script errors while rendering index.html: {script_errors}"
    finally:
        edge.close()
    return texts, cells


@pytest.mark.parametrize("view", ["S&OP", "Trend", "Manual", "Assumptions", "Stock panel", "Stock panel popup"])
def test_index_tab_rendered_text_is_reader_text(view, index_texts):
    texts, cells = index_texts
    lines = re.split(r"[\n\t]", texts[view])
    assert len([x for x in lines if x.strip()]) > 8, f"{view}: rendered text looks empty"
    found = violations(lines, _config_keys(), english_exempt=cells[view])
    assert not found, f"index.html {view}: reader-facing text carries project internals:\n" + "\n".join(found)


# ------------------------------------------------------------------ forecast/operation_plan.html (week 2)

def test_plan_page_static_visible_text_is_reader_text(plan_page):
    import html as _html
    with open(plan_page, encoding="utf-8") as f:
        text = f.read()
    lines = visible_lines(text)
    assert len(lines) > 40, "operation plan page: visible text extraction looks empty"
    names = {" ".join(_html.unescape(n).split()) for n in re.findall(r'<td class="name">(.*?)</td>', text)}      # product names: table cells from the price list
    found = violations(lines, _config_keys(), english_exempt=names)
    assert not found, "operation plan page: reader-facing text carries project internals:\n" + "\n".join(found)


def test_plan_page_rendered_text_is_reader_text(plan_page):
    edge = Edge(require_browser())
    try:
        edge.open(plan_page)
        text = edge.ev("document.body.innerText")
        cells = set(edge.ev("[...document.querySelectorAll('td, th')].map(c => c.innerText.trim())"))
        assert not [e for e in edge.errors if e.startswith("exception")], edge.errors
    finally:
        edge.close()
    lines = re.split(r"[\n\t]", text)
    assert len([x for x in lines if x.strip()]) > 40
    found = violations(lines, _config_keys(), english_exempt=cells)
    assert not found, "operation plan page: rendered reader-facing text carries project internals:\n" + "\n".join(found)


# ------------------------------------------------------------------ forecast/material_plan.html (week 3)

@pytest.fixture(scope="module")
def material_page(tmp_path_factory):
    """forecast/material_plan.html built by its builder from the recorded material plan into a temporary folder (skipped where the recorded plan is absent)."""
    import build_material_plan_page as bm
    import material_plan as mp
    cfg = mp.load_config()
    for k in ("output_material_month_file", "output_material_summary_file"):
        if not os.path.exists(mp.op.path_of(PROJECT_ROOT, cfg[k])):
            pytest.skip("SKIPPED, not passed: the recorded material plan is not on this machine")
    out = tmp_path_factory.mktemp("reader_text_material")
    return bm.build_page(out_path=str(out / "forecast" / "material_plan.html"))


def test_material_page_static_visible_text_is_reader_text(material_page):
    import html as _html
    with open(material_page, encoding="utf-8") as f:
        text = f.read()
    lines = visible_lines(text)
    assert len(lines) > 100, "material plan page: visible text extraction looks empty"
    names = {" ".join(_html.unescape(n).split()) for n in re.findall(r'<td class="name">(.*?)</td>', text)}      # material names: table cells from the item master
    found = violations(lines, _config_keys(), english_exempt=names)
    assert not found, "material plan page: reader-facing text carries project internals:\n" + "\n".join(found)


def test_material_page_rendered_text_is_reader_text(material_page):
    edge = Edge(require_browser())
    try:
        edge.open(material_page)
        text = edge.ev("document.body.innerText")
        cells = set(edge.ev("[...document.querySelectorAll('td, th')].map(c => c.innerText.trim())"))
        assert not [e for e in edge.errors if e.startswith("exception")], edge.errors
    finally:
        edge.close()
    lines = re.split(r"[\n\t]", text)
    assert len([x for x in lines if x.strip()]) > 100
    found = violations(lines, _config_keys(), english_exempt=cells)
    assert not found, "material plan page: rendered reader-facing text carries project internals:\n" + "\n".join(found)


# ------------------------------------------------------------------ 2026-10-08: no placeholder is left on any of the five pages
@pytest.mark.parametrize("name", ["sales_report.html", "inventory.html", "operation_plan.html", "material_plan.html"])
def test_no_brace_is_left_in_the_visible_text_of_a_built_page(name):
    path = os.path.join(PROJECT_ROOT, "forecast", name)
    if not os.path.exists(path):
        pytest.skip(f"SKIPPED, not passed: forecast/{name} is not built yet")
    with open(path, encoding="utf-8") as f:
        text = " ".join(visible_lines(f.read()))
    assert "{" not in text and "}" not in text, f"{name}: a placeholder or a brace is left in the visible text"
