"""Forward-test infrastructure: generates and logs forecasts for future
periods, to be compared against real actuals once those periods arrive.

WHY FORWARD TESTING MATTERS (see STATUS.md, 2026-08-31)
---------------------------------------------------------------------------
Every evaluation method used so far in this project — the single 6-month
holdout, rolling-origin validation, and the train/validation/test split —
scores a model against months that already existed in the data BEFORE the
model was chosen. The model designer (this pipeline) has already seen every
number involved, even in the "held out" test set, because that data was
pulled from the database before any evaluation ran. There is no way to rule
out that a model's apparent win reflects something specific to that already-
observed window rather than genuine forecasting skill.

Forward testing is different: it records a forecast for a period that has
not happened yet, then waits. When that period's actuals eventually arrive
in the database, they were generated by real future demand that no part of
this pipeline — including whichever human or process chose a model — could
have seen or reacted to in advance. It is the only evaluation immune to
hindsight, overfitting to a specific historical window, or the analyst
unconsciously favouring a model that happens to fit the known past well.

This script does not choose a model. It logs a forecast from every model
tested so far, for every pilot item, so that once real future actuals exist,
all models can be compared fairly on data none of them could have seen.
---------------------------------------------------------------------------

FILE FORMAT (output/summary/forward_test_log.csv)
Columns:
    itemcode          - pilot item code
    forecast_run_date - the date this forecast was generated (when this
                         script ran)
    data_cutoff_date  - the last date of actual data used to fit the model
                         (the true max date in the raw pull, not just the
                         last complete month)
    model             - which model produced this forecast
    config_version    - md5 hash (first 12 hex chars) of config.yaml's
                         content at forecast time, so results can be traced
                         to the exact configuration used, without requiring
                         a version field to be added to config.yaml itself
    horizon           - months ahead of the last complete training month
                         (1 through backtest_holdout_months)
    target_month      - the calendar month (YYYY-MM) this forecast is for
    forecast_qty      - the point forecast value
    actual_qty        - left EMPTY here; filled in later by
                         score_forward_test.py once the target month's
                         actuals exist in the database. Never fabricated.
"""
import hashlib
import logging
import os
import sys

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, os.path.dirname(__file__))
from models import get_models

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("forward_test")

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(PROJECT_ROOT, "config", "config.yaml")
DATA_DIR = os.path.join(PROJECT_ROOT, "output", "data")
SUMMARY_DIR = os.path.join(PROJECT_ROOT, "output", "summary")
FORWARD_TEST_LOG = os.path.join(SUMMARY_DIR, "forward_test_log.csv")


def load_config() -> dict:
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def config_version() -> str:
    with open(CONFIG_PATH, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()[:12]


def generate_forecasts(monthly: pd.DataFrame, item_codes: list, horizon: int, ma_windows: list) -> pd.DataFrame:
    models = get_models(ma_windows)
    run_date = pd.Timestamp.now().normalize().date().isoformat()
    cfg_ver = config_version()

    raw = pd.read_csv(os.path.join(DATA_DIR, "raw_pilot_sales_58items.csv"))
    data_cutoff = pd.to_datetime(raw["createDate"]).max().date().isoformat()

    records = []
    for item in item_codes:
        item_df = monthly[monthly["itemcode"] == item].sort_values("year_month")
        qty = item_df["qty"].to_numpy(dtype=float)
        last_month = pd.Period(item_df["year_month"].iloc[-1], freq="M")
        target_months = [str(last_month + i) for i in range(1, horizon + 1)]

        for model_name, model_fn in models.items():
            forecast = np.clip(model_fn(qty, horizon), 0, None)
            for h, (target_month, value) in enumerate(zip(target_months, forecast), start=1):
                records.append({
                    "itemcode": item, "forecast_run_date": run_date, "data_cutoff_date": data_cutoff,
                    "model": model_name, "config_version": cfg_ver, "horizon": h,
                    "target_month": target_month, "forecast_qty": round(float(value), 4),
                    "actual_qty": "",
                })
    return pd.DataFrame(records)


if __name__ == "__main__":
    config = load_config()
    horizon = config["backtest_holdout_months"]
    ma_windows = config["moving_average_windows"]

    monthly = pd.read_csv(os.path.join(DATA_DIR, "processed_pilot_sales_monthly.csv"))
    raw = pd.read_csv(os.path.join(DATA_DIR, "raw_pilot_sales_58items.csv"))
    max_date = pd.to_datetime(raw["createDate"]).max()
    month_end = max_date + pd.offsets.MonthEnd(0)
    if max_date < month_end:
        latest_month = str(pd.Period(max_date, freq="M"))
        monthly = monthly[monthly["year_month"] != latest_month]
        logger.info("Excluded partial month %s from fitting (data ends %s)", latest_month, max_date.date())

    item_codes = sorted(monthly["itemcode"].unique())
    logger.info("Generating %d-month-ahead forecasts for %d items, all models, using data through %s",
                horizon, len(item_codes), monthly["year_month"].max())

    new_forecasts = generate_forecasts(monthly, item_codes, horizon, ma_windows)

    if os.path.exists(FORWARD_TEST_LOG):
        existing = pd.read_csv(FORWARD_TEST_LOG, dtype=str)
        combined = pd.concat([existing, new_forecasts.astype(str)], ignore_index=True)
        combined = combined.drop_duplicates(subset=["itemcode", "model", "config_version", "target_month", "data_cutoff_date"], keep="last")
        combined.to_csv(FORWARD_TEST_LOG, index=False)
        logger.info("Appended to existing log: %d new rows, %d total rows after de-dup", len(new_forecasts), len(combined))
    else:
        new_forecasts.to_csv(FORWARD_TEST_LOG, index=False)
        logger.info("Created new forward-test log: %d rows (%d items x %d models x %d horizon)",
                    len(new_forecasts), len(item_codes), len(get_models(ma_windows)), horizon)

    print(f"\nForward-test log written: {FORWARD_TEST_LOG}")
    print(f"Rows this run: {len(new_forecasts)}")
    print(f"Target months covered: {sorted(new_forecasts['target_month'].unique())}")
    print("actual_qty is empty for all rows — these are real future periods, not fabricated.")
